/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Diseño;

import Archivos_Planos.fecha;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatLightOwlIJTheme;
import javax.swing.UIManager;

public class Empleados extends javax.swing.JFrame {

    fecha f1 = new fecha();

    public Empleados() {
        initComponents();
        this.setResizable(false);
        setLocationRelativeTo(null);
        mostrarfecha();
    }

    public void mostrarfecha() {

        Fecha_6.setText(f1.fe);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel37 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JSeparator();
        Fecha_6 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        Cliente_Fechan = new com.toedter.calendar.JDateChooser();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator14 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        Cliente_Cedula = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel62 = new javax.swing.JLabel();
        Cliente_Fechan1 = new com.toedter.calendar.JDateChooser();
        jLabel61 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jButton22 = new javax.swing.JButton();
        Cliente_Nombres = new javax.swing.JTextField();
        Cliente_Direccion = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        Cliente_Email = new javax.swing.JTextField();
        Cliente_Telefono = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Georgia", 3, 43)); // NOI18N
        jLabel36.setText("AROMA");
        jPanel9.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 47));

        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel9.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 13, 125));

        jLabel37.setFont(new java.awt.Font("Georgia", 1, 50)); // NOI18N
        jLabel37.setText("Datos");
        jPanel9.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(1347, 97, -1, 55));

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/xls-file_9680334 (1).png"))); // NOI18N
        jPanel9.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1567, 13, 85, 65));

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/archivo-pdf.png"))); // NOI18N
        jPanel9.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 90, 85, 65));

        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel9.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 20, 13, 128));

        Fecha_6.setEditable(false);
        Fecha_6.setBackground(new java.awt.Color(255, 255, 255));
        Fecha_6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Fecha_6.setBorder(null);
        jPanel9.add(Fecha_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 131, 31));

        jLabel38.setFont(new java.awt.Font("Impact", 0, 90)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(51, 0, 0));
        jLabel38.setText("Registro");
        jPanel9.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        jLabel40.setFont(new java.awt.Font("Georgia", 1, 35)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(204, 102, 0));
        jLabel40.setText("&");
        jPanel9.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel41.setFont(new java.awt.Font("Impact", 0, 90)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 102, 0));
        jLabel41.setText("Empleados");
        jPanel9.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, -1));

        jLabel42.setFont(new java.awt.Font("Georgia", 3, 43)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(51, 51, 51));
        jLabel42.setText("ESPÚMA");
        jPanel9.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, 55));

        jLabel63.setFont(new java.awt.Font("Georgia", 1, 50)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(204, 102, 0));
        jLabel63.setText("Exportar");
        jPanel9.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(1302, 24, 242, 55));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel39.setText("NIT: 0012023014403-12");
        jPanel9.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 530, 200, 22));

        jLabel44.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/telefono.png"))); // NOI18N
        jLabel44.setText("Telefono");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, -1, -1));

        jLabel45.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/identificacion.png"))); // NOI18N
        jLabel45.setText("Cedula");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, 30));
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 170, 22));

        jLabel47.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/perfil (1).png"))); // NOI18N
        jLabel47.setText("Nombres");
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel48.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cumpleanos.png"))); // NOI18N
        jLabel48.setText("Fecha De Nacimiento");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        jLabel49.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lavabo.png"))); // NOI18N
        jLabel49.setText("Genero");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 100, -1));

        jLabel50.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/direccion-de-correo-electronico.png"))); // NOI18N
        jLabel50.setText("Email");
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        jLabel51.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gps.png"))); // NOI18N
        jLabel51.setText("Direccion");
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));
        jPanel1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 550, 22));
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 180, 22));

        Cliente_Fechan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(Cliente_Fechan, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 200, 40));
        jPanel1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 200, 22));
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 230, 22));
        jPanel1.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 200, 22));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombres", "Genero", "Direccion", "Email", "Telefono", "FechaNacimiento", "FechaIngreso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 80, 742, 490));

        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 25, 9, 530));

        jButton4.setBackground(new java.awt.Color(255, 102, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 90, 49));

        Cliente_Cedula.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jPanel1.add(Cliente_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 170, 40));

        jButton2.setBackground(new java.awt.Color(255, 102, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 238, 110, 80));

        jLabel57.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel57.setText("Actualizar");
        jPanel1.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-usuario (3).png"))); // NOI18N
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 93, 110, 80));

        jLabel58.setBackground(new java.awt.Color(255, 102, 0));
        jLabel58.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel58.setText("Agregar");
        jPanel1.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel59.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel59.setText("Eliminar");
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 102, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/basura.png"))); // NOI18N
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 383, 110, 80));

        jLabel62.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendario.png"))); // NOI18N
        jLabel62.setText("Fecha De Ingreso");
        jPanel1.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, -1, -1));

        Cliente_Fechan1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(Cliente_Fechan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 200, 40));
        jPanel1.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 200, 22));

        jSeparator15.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator15.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 25, 15, 557));

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion (2).png"))); // NOI18N
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 20, 50, 50));

        Cliente_Nombres.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jPanel1.add(Cliente_Nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 230, 40));

        Cliente_Direccion.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jPanel1.add(Cliente_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 560, 70));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 180, 40));

        Cliente_Email.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jPanel1.add(Cliente_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 200, 40));

        Cliente_Telefono.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jPanel1.add(Cliente_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 200, 40));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, 581, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1679, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1679, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // UIManager.setLookAndFeel(new FlatLightLaf());

            FlatLightOwlIJTheme.setup();
            UIManager.put("Button.arc", 200);
            UIManager.put("TextComponent.arc", 100);
            UIManager.put("Component.arc", 100);

        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cliente_Cedula;
    private javax.swing.JTextField Cliente_Direccion;
    private javax.swing.JTextField Cliente_Email;
    private com.toedter.calendar.JDateChooser Cliente_Fechan;
    private com.toedter.calendar.JDateChooser Cliente_Fechan1;
    private javax.swing.JTextField Cliente_Nombres;
    private javax.swing.JTextField Cliente_Telefono;
    private javax.swing.JTextField Fecha_6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
