/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Diseño;

import Archivos_Planos.Conexion;
import Archivos_Planos.fecha;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatLightOwlIJTheme;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

public class Empleados extends javax.swing.JFrame {

    Conexion Conn = new Conexion("postgres", "123456789", "Cafeteria", "5432", "localhost");
    DefaultTableModel Y = new DefaultTableModel();

    fecha f1 = new fecha();

    public Empleados() {
        initComponents();
        this.setResizable(false);
        setLocationRelativeTo(null);
        String[] ids = {"Cedula", "Nombres", "Genero", "Direccion", "Email", "Telefono", "Fecha de Nacimiento", "Fecha de Ingreso"};
        Tabla_Empleado.setModel(Y);
        Y.setColumnIdentifiers(ids);
        mostrarfecha();
        CargarDatos();
    }

    public void mostrarfecha() {
        Fecha_6.setText(f1.fe);
    }

    public void Sugerencia(String cad) {
        try {
            Conn.Conexionpostgres();
            String S = "SELECT * FROM \"Empleado\" WHERE \"Nombre\" LIKE '" + cad + "%'";
            ResultSet Rs = Conn.Consultar(S);

            String Columnas[] = {"Cedula", "Nombres", "Genero", "Direccion", "Email", "Telefono", "Fecha de Nacimiento", "Fecha de Ingreso"};
            DefaultTableModel ModelEmpleado = new DefaultTableModel(Columnas, 0);
            Tabla_Empleado.setModel(ModelEmpleado);
            while (Rs.next()) {
                ModelEmpleado.addRow(new Object[]{
                    Rs.getLong("Cedula"),
                    Rs.getString("Nombre"),
                    Rs.getString("Genero"),
                    Rs.getString("Direccion"),
                    Rs.getString("Email"),
                    Rs.getLong("Telefono"),
                    Rs.getDate("FechaDeNacimiento"),
                    Rs.getDate("FechaDeIngreso")

                });
            }
            Rs.close();
            Conn.cerrar();

        } catch (ClassNotFoundException | SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void CargarDatos() {
        Y.setRowCount(0);
        try {
            Conn.Conexionpostgres();
            String C = "SELECT * FROM \"Empleado\"";
            ResultSet Rs = Conn.Consultar(C);

            while (Rs.next()) {
                Y.addRow(new Object[]{
                    Rs.getLong("Cedula"),
                    Rs.getString("Nombre"),
                    Rs.getString("Genero"),
                    Rs.getString("Direccion"),
                    Rs.getString("Email"),
                    Rs.getLong("Telefono"),
                    Rs.getDate("FechaDeNacimiento"),
                    Rs.getDate("FechaDeIngreso")
                });
            }
            Rs.close();
            Conn.cerrar();
        } catch (ClassNotFoundException | SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel37 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JSeparator();
        Fecha_6 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        Empleado_Telefono = new javax.swing.JTextField();
        Empleado_Email = new javax.swing.JTextField();
        Empleado_Direccion = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        Empleado_Cedula = new javax.swing.JTextField();
        Empleado_Nombres = new javax.swing.JTextField();
        Empleado_Genero = new javax.swing.JComboBox<>();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        Empleado_Fechan = new com.toedter.calendar.JDateChooser();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Empleado = new javax.swing.JTable();
        jSeparator14 = new javax.swing.JSeparator();
        Buscar = new javax.swing.JButton();
        Empleado_Buscar = new javax.swing.JTextField();
        Actualizar = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        Agregar = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        Eliminar = new javax.swing.JButton();
        jLabel62 = new javax.swing.JLabel();
        Empleado_FechaR = new com.toedter.calendar.JDateChooser();
        jLabel61 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Georgia", 3, 43)); // NOI18N
        jLabel36.setText("AROMA");
        jPanel9.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 47));

        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel9.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 21, 13, 125));

        jLabel37.setFont(new java.awt.Font("Georgia", 3, 50)); // NOI18N
        jLabel37.setText("Datos");
        jPanel9.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 90, -1, 55));

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/xls-file_9680334 (1).png"))); // NOI18N
        jPanel9.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 10, 85, 65));

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/archivo-pdf.png"))); // NOI18N
        jPanel9.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 80, 85, 65));

        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel9.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1271, 24, 13, 128));

        Fecha_6.setEditable(false);
        Fecha_6.setBackground(new java.awt.Color(255, 255, 255));
        Fecha_6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Fecha_6.setBorder(null);
        jPanel9.add(Fecha_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 131, 31));

        jLabel38.setFont(new java.awt.Font("Impact", 0, 90)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(51, 0, 0));
        jLabel38.setText("Registro");
        jPanel9.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        jLabel40.setFont(new java.awt.Font("Georgia", 1, 35)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(204, 102, 0));
        jLabel40.setText("&");
        jPanel9.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel41.setFont(new java.awt.Font("Impact", 0, 90)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 102, 0));
        jLabel41.setText("Empleados");
        jPanel9.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, -1));

        jLabel42.setFont(new java.awt.Font("Georgia", 3, 43)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(51, 51, 51));
        jLabel42.setText("PERFUME");
        jPanel9.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, 55));

        jLabel63.setFont(new java.awt.Font("Georgia", 3, 50)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(204, 102, 0));
        jLabel63.setText("Exportar");
        jPanel9.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 20, 242, 55));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel39.setText("NIT: 0012023014403-12");
        jPanel9.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 200, 22));

        jLabel44.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/telefono.png"))); // NOI18N
        jLabel44.setText("Telefono");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, -1, -1));

        Empleado_Telefono.setText("\n");
        Empleado_Telefono.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(Empleado_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 200, 32));

        Empleado_Email.setText(" ");
        Empleado_Email.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(Empleado_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 200, 32));

        Empleado_Direccion.setText(" ");
        Empleado_Direccion.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(Empleado_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 554, 60));

        jLabel45.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/identificacion.png"))); // NOI18N
        jLabel45.setText("Cedula");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, 30));
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 150, 22));

        jLabel47.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/perfil (1).png"))); // NOI18N
        jLabel47.setText("Nombres");
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel48.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cumpleanos.png"))); // NOI18N
        jLabel48.setText("Fecha De Nacimiento");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        jLabel49.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lavabo.png"))); // NOI18N
        jLabel49.setText("Genero");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 100, -1));

        jLabel50.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/direccion-de-correo-electronico.png"))); // NOI18N
        jLabel50.setText("Email");
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        jLabel51.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gps.png"))); // NOI18N
        jLabel51.setText("Direccion");
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        Empleado_Cedula.setText("\n");
        Empleado_Cedula.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(Empleado_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 150, 32));

        Empleado_Nombres.setText("\n");
        Empleado_Nombres.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(Empleado_Nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 200, 32));

        Empleado_Genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        Empleado_Genero.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(Empleado_Genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 181, 32));
        jPanel1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 450, 22));
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 169, 22));

        Empleado_Fechan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(Empleado_Fechan, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 200, 32));
        jPanel1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 200, 22));
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 200, 22));
        jPanel1.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 200, 22));

        Tabla_Empleado = new javax.swing.JTable(){
            public boolean isCellEditable(int row , int col){
                return false;
            }
        };
        Tabla_Empleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabla_Empleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_EmpleadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_Empleado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 80, 742, 490));

        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(916, 25, 9, 530));

        Buscar.setBackground(new java.awt.Color(255, 102, 0));
        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 90, 49));

        Empleado_Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Empleado_BuscarKeyReleased(evt);
            }
        });
        jPanel1.add(Empleado_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, 581, 30));

        Actualizar.setBackground(new java.awt.Color(255, 102, 0));
        Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 238, 100, 70));

        jLabel57.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel57.setText("Actualizar");
        jPanel1.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 314, -1, -1));

        Agregar.setBackground(new java.awt.Color(255, 102, 0));
        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-usuario (3).png"))); // NOI18N
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        jPanel1.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 93, 100, 70));

        jLabel58.setBackground(new java.awt.Color(255, 102, 0));
        jLabel58.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel58.setText("Agregar");
        jPanel1.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 169, -1, -1));

        jLabel59.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel59.setText("Eliminar");
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 459, -1, -1));

        Eliminar.setBackground(new java.awt.Color(255, 102, 0));
        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/basura.png"))); // NOI18N
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 383, 100, 70));

        jLabel62.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendario.png"))); // NOI18N
        jLabel62.setText("Fecha De Ingreso");
        jPanel1.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, -1));

        Empleado_FechaR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(Empleado_FechaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 200, 32));
        jPanel1.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 200, 22));

        jSeparator15.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator15.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 25, 15, 557));

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion (2).png"))); // NOI18N
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 44, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1679, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        try {
            Conn.Conexionpostgres();
        } catch (ClassNotFoundException | SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
        }

        String U = "UPDATE public.\"Empleado\" SET "
                + "\"Cedula\" = '" + Empleado_Cedula.getText() + "',"
                + "\"Nombre\" = '" + Empleado_Nombres.getText() + "',"
                + "\"FechaDeNacimiento\" = '" + new java.sql.Date(Empleado_Fechan.getDate().getTime()) + "',"
                + "\"Genero\" = '" + Empleado_Genero.getSelectedItem().toString() + "',"
                + "\"Telefono\" = '" + Empleado_Telefono.getText() + "',"
                + "\"Email\" = '" + Empleado_Email.getText() + "',"
                + "\"Direccion\" = '" + Empleado_Direccion.getText() + "',"
                + "\"FechaDeIngreso\" = '" + new java.sql.Date(Empleado_FechaR.getDate().getTime()) + "'"
                + "WHERE \"Cedula\" = '" + Empleado_Cedula.getText() + "'";
        try {
            Conn.Actualizar(U);
            CargarDatos();
            Conn.cerrar();
        } catch (SQLException ex) {
            Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
        }

        Empleado_Cedula.setText("");
        Empleado_Nombres.setText("");
        Empleado_Fechan.setDate(null);
        Empleado_Genero.setSelectedItem(null);
        Empleado_Telefono.setText("");
        Empleado_Email.setText("");
        Empleado_Direccion.setText("");
        Empleado_FechaR.setDate(null);

    }//GEN-LAST:event_ActualizarActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        try {
            Conn.Conexionpostgres();

        } catch (ClassNotFoundException | SQLException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(Empleados.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        String A = "INSERT INTO \"Empleado\"(\n"
                + " \"Cedula\",\"Nombre\",\"FechaDeNacimiento\",\"Genero\",\"Telefono\",\"Email\",\"Direccion\",\"FechaDeIngreso\")" + "VALUES ('" + Empleado_Cedula.getText() + "','" + Empleado_Nombres.getText() + "','" + Empleado_Fechan.getDate() + "','" + Empleado_Genero.getSelectedItem() + "','" + Empleado_Telefono.getText() + "','" + Empleado_Email.getText() + "','" + Empleado_Direccion.getText() + "','" + Empleado_FechaR.getDate() + "');";

        try {
            Conn.Actualizar(A);
            CargarDatos();
            Conn.cerrar();

        } catch (SQLException ex) {
            Logger.getLogger(Empleados.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

        Empleado_Cedula.setText("");
        Empleado_Nombres.setText("");
        Empleado_Fechan.setDate(null);
        Empleado_Genero.setSelectedItem(null);
        Empleado_Telefono.setText("");
        Empleado_Email.setText("");
        Empleado_Direccion.setText("");
        Empleado_FechaR.setDate(null);

    }//GEN-LAST:event_AgregarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        int filaseleccionada = Tabla_Empleado.getSelectedRow();
        if (filaseleccionada >= 0) {

            int ValorEliminar = Integer.parseInt(Y.getValueAt(filaseleccionada, 0).toString());
            Y.removeRow(filaseleccionada);

            try {
                Conn.Conexionpostgres();

            } catch (ClassNotFoundException | SQLException | InstantiationException | IllegalAccessException ex) {
                Logger.getLogger(Clientes.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

            String E = "DELETE FROM public.\"Empleado\"\n" + "WHERE \"Cedula\"=" + (ValorEliminar);

            try {
                Conn.Actualizar(E);
                Conn.cerrar();

            } catch (SQLException ex) {
                Logger.getLogger(Clientes.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void Empleado_BuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Empleado_BuscarKeyReleased
        String Cad = Empleado_Buscar.getText().trim();
        Sugerencia(Cad);
    }//GEN-LAST:event_Empleado_BuscarKeyReleased

    private void Tabla_EmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_EmpleadoMouseClicked
        int fila = Tabla_Empleado.getSelectedRow();

        if (fila >= 0) {
            Empleado_Cedula.setText(Tabla_Empleado.getValueAt(fila, 0).toString());
            Empleado_Nombres.setText(Tabla_Empleado.getValueAt(fila, 1).toString());
            Empleado_Genero.setSelectedItem(Tabla_Empleado.getValueAt(fila, 2).toString());
            Empleado_Direccion.setText(Tabla_Empleado.getValueAt(fila, 3).toString());
            Empleado_Email.setText(Tabla_Empleado.getValueAt(fila, 4).toString());
            Empleado_Telefono.setText(Tabla_Empleado.getValueAt(fila, 5).toString());

            java.sql.Date fecha = (java.sql.Date) Tabla_Empleado.getValueAt(fila, 6);
            java.util.Date fechatransformada = new java.util.Date(fecha.getTime());
            Empleado_Fechan.setDate(fechatransformada);

            java.sql.Date fecha2 = (java.sql.Date) Tabla_Empleado.getValueAt(fila, 7);
            java.util.Date fechatransformada2 = new java.util.Date(fecha2.getTime());
            Empleado_FechaR.setDate(fechatransformada2);
        }
    }//GEN-LAST:event_Tabla_EmpleadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // UIManager.setLookAndFeel(new FlatLightLaf());

            FlatLightOwlIJTheme.setup();
            UIManager.put("Button.arc", 200);

        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField Empleado_Buscar;
    private javax.swing.JTextField Empleado_Cedula;
    private javax.swing.JTextField Empleado_Direccion;
    private javax.swing.JTextField Empleado_Email;
    private com.toedter.calendar.JDateChooser Empleado_FechaR;
    private com.toedter.calendar.JDateChooser Empleado_Fechan;
    private javax.swing.JComboBox<String> Empleado_Genero;
    private javax.swing.JTextField Empleado_Nombres;
    private javax.swing.JTextField Empleado_Telefono;
    private javax.swing.JTextField Fecha_6;
    private javax.swing.JButton Salir;
    private javax.swing.JTable Tabla_Empleado;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    // End of variables declaration//GEN-END:variables
}
